window.CONSTANT_FEEDS = [
  {title:"ABC News Live",kind:"news",type:"youtube-channel",channel:"UCBi2mrWuNuyYy4gbM6fU18Q"},
  {title:"Sky News",kind:"news",type:"youtube-channel",channel:"UCoMdktPbSTixAyNGwb-UYkQ"},
  {title:"Al Jazeera English",kind:"news",type:"youtube-channel",channel:"UCNye-wNBqNL5ZzHSJj3l8Bg"},
  {title:"France 24 English",kind:"news",type:"youtube-channel",channel:"UCQfwfsi5VrQ8yKZ-UWmYOJQ"},
  {title:"NASA Live",kind:"live",type:"youtube-channel",channel:"UCLA_DiR1FfKNvjuUpBHmylQ"},
  {title:"NBC News",kind:"news",type:"youtube-channel",channel:"UCeY0bbntWzzVIaj2z3QigXg"},
  {title:"CBS News",kind:"news",type:"youtube-channel",channel:"UC8p1vAjTFkwT6dwPqp2b0Mw"},
  {title:"C-SPAN",kind:"news",type:"youtube-channel",channel:"UCb--64Gl51jIEVE0VtQdQcg"},
  {title:"Associated Press",kind:"news",type:"youtube-channel",channel:"UC52X5wxOL_s5yw0dQk7NtgA"},
  {title:"Reuters",kind:"news",type:"youtube-channel",channel:"UChAOWCqZ6p1OPVYSdVsO_0A"},
  {title:"Bloomberg Television",kind:"news",type:"youtube-channel",channel:"UCIALMKvObZNtJ6AmdCLP7Lg"},
  {title:"DW News",kind:"news",type:"youtube-channel",channel:"UCknLrEdhRCp1aegoAuM0BgQ"},
  {title:"Euronews English",kind:"news",type:"youtube-channel",channel:"UCSrZ3UV4jOidv8ppoVuvW9Q"},
  {title:"TRT World",kind:"news",type:"youtube-channel",channel:"UC7fWeaHhqgQ8N0Z1dAhOMzw"},
  {title:"CGTN",kind:"news",type:"youtube-channel",channel:"UCgrNz-aDmcr2uuto8_DL2jg"},
  {title:"PBS NewsHour",kind:"news",type:"youtube-channel",channel:"UC6ZFN9Tx6xh-skXCuRHCDpQ"},
  {title:"United Nations",kind:"news",type:"youtube-channel",channel:"UC5O114-PQNYkurlTg6hekZw"},
  {title:"Africanews",kind:"news",type:"youtube-channel",channel:"UC1_E8Nl2KQdIfId3sRS05Yg"},
  {title:"USA TODAY Live",kind:"news",type:"youtube-channel",channel:"UCP6HGa63sBC7-KHtkme-p-A"},
  {title:"The Weather Channel",kind:"webcam",type:"youtube-channel",channel:"UC_gSrlG3hK6v5l9O2vYxU2A"},
  {title:"LA I-110 Ave 26",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d7/cctv/image/i110196avenue26offramp/i110196avenue26offramp.jpg"},
  {title:"LA I-5 Slauson",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d7/cctv/image/i52slausonave/i52slausonave.jpg"},
  {title:"LA I-5 Zoo Drive",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d7/cctv/image/i531zoodrive/i531zoodrive.jpg"},
  {title:"LA I-5 Olive",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d7/cctv/image/i537olive/i537olive.jpg"},
  {title:"LA I-5 Burbank",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d7/cctv/image/i540northofburbankblvd/i540northofburbankblvd.jpg"},
  {title:"LA I-5 Meadowdale",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d7/cctv/image/i525meadowdale/i525meadowdale.jpg"},
  {title:"SF I-580 / SR-24",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d4/cctv/image/tv102i580westofsr24/tv102i580westofsr24.jpg"},
  {title:"SF I-280 Daly Blvd",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d4/cctv/image/tv327i280johndalyblvd/tv327i280johndalyblvd.jpg"},
  {title:"SF I-680 N Main",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d4/cctv/image/tv216i680northmainstreet/tv216i680northmainstreet.jpg"},
  {title:"SF US-101 Wilfred",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d4/cctv/image/tv127us101wilfredavenue/tv127us101wilfredavenue.jpg"},
  {title:"SF SR-4 Lone Tree",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d4/cctv/image/tv224sr4lonetreeway/tv224sr4lonetreeway.jpg"},
  {title:"SF SR-238 Ashland",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d4/cctv/image/tv709sr238southofashlandavenue/tv709sr238southofashlandavenue.jpg"},
  {title:"SAC I-5 Pocket",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d3/cctv/image/hwy5atpocket/hwy5atpocket.jpg"},
  {title:"SAC I-5 Florin",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d3/cctv/image/hwy5atflorin/hwy5atflorin.jpg"},
  {title:"SAC I-5 Gloria",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d3/cctv/image/hwy5atgloria/hwy5atgloria.jpg"},
  {title:"SAC I-5 43rd",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d3/cctv/image/hwy5at43rdave/hwy5at43rdave.jpg"},
  {title:"SAC I-5 Seamas",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d3/cctv/image/hwy5atseamas/hwy5atseamas.jpg"},
  {title:"SAC I-5 Sutterville",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d3/cctv/image/hwy5atsutterville/hwy5atsutterville.jpg"},
  {title:"SD SR-163 Friars",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d11/cctv/image/c348sr163friarsneb/c348sr163friarsneb.jpg"},
  {title:"SD SR-163 / I-8",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d11/cctv/image/c003sr163i8/c003sr163i8.jpg"},
  {title:"SD I-8 Hotel Circle",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d11/cctv/image/c005i8hotelcircle/c005i8hotelcircle.jpg"},
  {title:"SD I-8 Taylor",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d11/cctv/image/c006i8justeastoftaylor/c006i8justeastoftaylor.jpg"},
  {title:"SD SR-163 south of I-8",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d11/cctv/image/c002sr163justsouthofi8/c002sr163justsouthofi8.jpg"},
  {title:"IE I-10 LA County Line",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d8/cctv/image/i1001lacountyline/i1001lacountyline.jpg"},
  {title:"IE I-10 Monte Vista",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d8/cctv/image/i1002eastofmontevista/i1002eastofmontevista.jpg"},
  {title:"IE I-10 Central",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d8/cctv/image/i1003central/i1003central.jpg"},
  {title:"IE I-10 Benson",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d8/cctv/image/i1004bensonavenue/i1004bensonavenue.jpg"},
  {title:"IE I-10 Mountain",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d8/cctv/image/i1005eastofmountainavenue/i1005eastofmountainavenue.jpg"},
  {title:"IE I-10 Euclid",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d8/cctv/image/i1006westofeuclid/i1006westofeuclid.jpg"},
  {title:"OC I-5 Magnolia",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d12/cctv/image/i51northofmagnoliaavenuesouthofsr91/i51northofmagnoliaavenuesouthofsr91.jpg"},
  {title:"OC SR-91 Beach",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d12/cctv/image/sr912beachboulevard/sr912beachboulevard.jpg"},
  {title:"OC SR-57 / SR-22",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d12/cctv/image/sr5712sr22/sr5712sr22.jpg"},
  {title:"OC SR-91 / 55",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d12/cctv/image/sr915rte55hmpole/sr915rte55hmpole.jpg"},
  {title:"OC SR-57 Ball Rd",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d12/cctv/image/sr576ballroad/sr576ballroad.jpg"},
  {title:"OC I-5 Harbor",kind:"traffic",type:"image",refresh:12000,url:"https://cwwp2.dot.ca.gov/data/d12/cctv/image/i57harborboulevard/i57harborboulevard.jpg"}
];
